#!/bin/bash
PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

DIR=/Users/bbnytech/Lessons
DATE=`date +%Y-%m-%d`

ffmpeg -i $DIR/$DATE/heb.flv -vn -ar 44100 -ac 2 -ab 48k -f mp3 $DIR/$DATE/heb.mp3 &
ffmpeg -i $DIR/$DATE/rus.flv -vn -ar 44100 -ac 2 -ab 48k -f mp3 $DIR/$DATE/rus.mp3 &
ffmpeg -i $DIR/$DATE/eng.flv -vn -ar 44100 -ac 2 -ab 48k -f mp3 $DIR/$DATE/eng.mp3

times=()

for f in $DIR/$DATE/*.mp3; do
	_t=$(ffprobe "$f" 2>&1 | grep Duration | cut -d ' ' -f 4 | sed s/,// | awk -F: '{print $2":"$3 }')
	times+=("$_t")
done

sorted=($(printf '%s\n' "${times[@]}" | sort))

min=$(echo ${sorted[0]} | awk -F: '{print $1*1}') #find the smallest minute

ht=$(ffprobe $DIR/$DATE/heb.mp3 2>&1 | grep Duration | cut -d ' ' -f 4 | sed s/,// | awk -F: '{print 0 ":" $2-"'"$min"'" ":" $3}')
rt=$(ffprobe $DIR/$DATE/rus.mp3 2>&1 | grep Duration | cut -d ' ' -f 4 | sed s/,// | awk -F: '{print 0 ":" $2-"'"$min"'" ":" $3}')
et=$(ffprobe $DIR/$DATE/eng.mp3 2>&1 | grep Duration | cut -d ' ' -f 4 | sed s/,// | awk -F: '{print 0 ":" $2-"'"$min"'" ":" $3}')

ffmpeg -i $DIR/$DATE/heb.flv -vcodec copy -acodec aac -ab 96k -strict experimental -async 1 -ss $ht $DIR/$DATE/heb.mp4 &
ffmpeg -i $DIR/$DATE/rus.flv -vcodec copy -acodec aac -ab 96k -strict experimental -async 1 -ss $rt $DIR/$DATE/rus.mp4 &
ffmpeg -i $DIR/$DATE/eng.flv -vcodec copy -acodec aac -ab 96k -strict experimental -async 1 -ss $et $DIR/$DATE/eng.mp4 